### ISSUE TITLE
Possible silent failure from discord client?

### ISSUE THREAD

**Issue by dktrotti** [kchin28/movieBot#17]
MovieBot went offline, but was still running. When I checked its log, there was only a "Hello World" message. Is it possible that there was an error from the discord client that was ignored? Either way, some extra logging could be useful.

**Comment by Loonman** [comment]
More logging would probably be good, but I don't think we can triage this without more info

**Comment by Loonman** [comment]
https://github.com/discord-net/Discord.Net/issues/1334
Not my problem
